### ISSUE TITLE
1.20.2/3/4 support

### ISSUE THREAD

**Issue by zumbiepig** [Jab125/forge-early-loading-screen#3]
Could you add support for 1.20.2?

**Comment by Jab125** [comment]
I will when neoforge ports to 1.20.2

**Comment by zumbiepig** [comment]
Forge has updated to 1.20.2 now.

**Comment by Jab125** [comment]
will add support soon

**Comment by zax71** [comment]
Just wondering if there are any updates? Really like having this mod on :)

**Comment by Jab125** [comment]
I think I'll skip 1.20.2 and do 1.20.4

**Comment by zumbiepig** [comment]
thats fine

**Comment by Jab125** [comment]
i'm nearly finished with the port, will be out in a few minutes

**Comment by Jab125** [comment]
https://modrinth.com/mod/forge-early-loading-screen-fabric/version/0.2.0
