### ISSUE TITLE
Minecraft crashes with mod installed

### ISSUE THREAD

**Issue by zumbiepig** [Jab125/forge-early-loading-screen#4]
When I start Minecraft, it crashes. Why is this happening? The instance runs fine when I disable the mod.
Logs: https://mclo.gs/kfJMnN3

**Comment by Jab125** [comment]
does this happen with the mod by itself? I cannot reproduce this error with a modpack running Fabulously Optimised 5.8.0-alpha.2 with the mod added.

**Comment by Jab125** [comment]
Export the modpack as an .mrpack and send it here

**Comment by zumbiepig** [comment]
Sorry Github doesn't support .mrpack, so here's my mod list:
I have copied my instance without any config (just mods folder), and it still crashes.

EDIT: Here is a .mrpack with the file extension changed manually, you need to change it back. [Fabric.zip](https://github.com/Jab125/forge-early-loading-screen/files/13687486/Fabric.zip)

- [Iris](https://modrinth.com/mod/YL57xq9U) [1.6.14] by coderbot, IMS212, Justsnoopy30, FoundationGames
- [uku's Armor HUD](https://modrinth.com/mod/wF189hn9) [0.4.2+mc1.20.3] by BerdinskiyBear, uku
- [Zoomify](https://modrinth.com/mod/w7ThoJFB) [2.12.0] by isXander
- [Litematica](https://www.curseforge.com/projects/308892) [0.17.0] by masa
- [Indium](https://modrinth.com/mod/Orvt0mRa) [1.0.27+mc1.20.1] by comp500
- [Hold That Chunk](https://modrinth.com/mod/LXJlc5WJ) [2.1.0] by dlee13
- [Sodium Extra](https://modrinth.com/mod/PtjYWJkn) [0.5.3+mc1.20.2-build.114] by FlashyReese
- [ViaFabricPlus](https://modrinth.com/mod/rIC2XJV4) [3.0.2] by FlorianMichael/EnZaXD, RK_01
- [Better Mount HUD](https://modrinth.com/mod/kqJFAPU9) [1.2.2] by Lortseam
- [Forge Early Loading Screen](https://modrinth.com/mod/qPqMrMUl) [0.2.0] by Jab125
- [Sodium](https://modrinth.com/mod/AANobbMI) [0.5.5] by @jellysquid3
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0.91.2+1.20.4] by FabricMC
- [ImmediatelyFast](https://modrinth.com/mod/5ZwdcRci) [1.2.8+1.20.4] by RK_01
- [MaLiLib](https://www.curseforge.com/projects/303119) [0.18.0] by masa
- [Simple Voice Chat](https://modrinth.com/mod/9eGKb6K1) [1.20.4-2.4.31] by Max Henkel
- [Gamma Utils](https://modrinth.com/mod/wdLuzzEP) [1.7.18] by Sjouwer
- [Dynamic FPS](https://modrinth.com/mod/LQ3K71Q1) [3.2.1] by juliand665, LostLuma
- [AppleSkin](https://modrinth.com/mod/EsAfCjCV) [2.5.1+mc1.20.3] by squeek502
- [e4mc](https://modrinth.com/mod/qANg5Jrr) [4.0.1] by skyevg
- [Remove Reloading Screen](https://modrinth.com/mod/ZP7xHXtw) [3.2.3+mc1.20.2-fabric] by dima_dencep
- [FerriteCore](https://modrinth.com/mod/uXXizFIs) [6.0.3] by malte0811
- [Better Hand Bobbing](https://modrinth.com/mod/2FJYrSBD) [1.6.3] by IrisJS
- [EmuNO](https://modrinth.com/mod/RLrPqrNI) [1.1.1] by RyanCaoDev
- [LazyDFU](https://modrinth.com/mod/hvFnDODi) [0.1.3] by tuxed
- [Mod Menu](https://modrinth.com/mod/mOgUt4GM) [9.0.0-pre.1] by Prospector, haykam821, TerraformersMC
- [WorldEditCUI](https://www.curseforge.com/projects/402098) [1.20.2+01] by lahwran, yetanotherx, Mumfrey, TomyLobo, mikroskeem
- [YetAnotherConfigLib](https://modrinth.com/mod/1eAoo2KR) [3.3.1+1.20.4] by isXander
- [Capes](https://modrinth.com/mod/89Wsn8GD) [1.5.3+1.20.2] by Cael
- [MoreChatHistory](https://modrinth.com/mod/8qkXwOnk) [1.1.1] by JackFred
- [Paginated Advancements](https://modrinth.com/mod/pJogNFap) [2.4.2] by DaFuqs
- [EntityCulling](https://modrinth.com/mod/NNAgCjsB) [1.6.3.1] by tr7zw
- [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1.10.16+kotlin.1.9.21] by FabricMC
- [ukulib](https://modrinth.com/mod/Y8uFrUil) [1.1.0+1.20.3] by uku
- [Cloth Config v13](https://modrinth.com/mod/9s6osm5g) [13.0.114] by shedaniel
- [Reese's Sodium Options](https://modrinth.com/mod/Bh37bMuy) [1.7.0+mc1.20.2-build.97] by FlashyReese
- [Status Effect Bars](https://modrinth.com/mod/x02cBj9Y) [1.0.4] by Neecko5b84
- [Starlight](https://modrinth.com/mod/H8CaAYZC) [1.1.3+fabric.f5dcd1a] by Spottedleaf

**Comment by orionzleon** [comment]
See above comment, however here is a .mrpack with the file extension changed, so you need to change it back to .mrpack
[Fabric.zip](https://github.com/Jab125/forge-early-loading-screen/files/13687486/Fabric.zip)

**Comment by Jab125** [comment]
Does [0.3.0](https://modrinth.com/mod/forge-early-loading-screen-fabric/version/0.3.0) fix this?

**Comment by zumbiepig** [comment]
ill test this later, as im currently learning how to make my own mod right
now

**Comment by zumbiepig** [comment]
nope it doesnt work. it crashes even earlier in the launch sequence. logs:
https://mclo.gs/VTqqUaK

**Comment by Jab125** [comment]
There shouldn't be a crash now, since the mod will work even if patching fails.
