### ISSUE TITLE
Crash on linux with AOF7 modpack

### ISSUE THREAD

**Issue by Yoosk** [Jab125/forge-early-loading-screen#7]
Game is crashing before it even can create crash-report so the latest.log is only available option, added the mod that AOF7 modpack and this is the outcome: https://mclo.gs/f0jOY7x

**Comment by Jab125** [comment]
Try adding `-Djdk.attach.allowAttachSelf=true` to JVM args.

**Comment by Yoosk** [comment]
this doesnt seem right either https://mclo.gs/lsgqsf9

**Comment by Jab125** [comment]
Does this happen with the mod by itself?
And does it vary depending on what launcher you are using?

**Comment by Jab125** [comment]
The mod should now not crash if it failed to patch classes properly.
